export type SbuId = 'masstel' | 'nexta' | 'joystar' | 'meup' | 'support'

export const sbuPresets = {
  masstel: {
    metric: 'Doanh thu Feature Phone & Kid',
    x: '227 tỷ (T1–T4/2026)',
    y: '650 tỷ',
    z: '31/12/2026',
    reason:
      'Kênh Master + KA còn dư địa tăng sản lượng. Đội sale có thể tăng training điểm bán từ 2 buổi/tuần lên 5 buổi.',
    lm1desc: 'Số điểm bán FP được training / khu vực / tuần',
    lm1target: 'Theo KPI kênh phân phối',
    lm1owner: 'GĐ kênh (Yến Hoa / Sỹ Hiếu / Văn Hưng)',
    lm2desc: 'Sản lượng FP & Kid xuất kho / tuần theo kênh',
    lm2target: 'KPI xuất kho theo kế hoạch tháng',
    lm2owner: 'Trưởng phòng KD + Vận hành',
    sbwig: 'DT FP & Kid: 227 tỷ → 650 tỷ trước 31/12/2026',
    sblag: 'Doanh thu FP & Kid',
  },
  nexta: {
    metric: 'Doanh thu EdTech / Lớp học thông minh',
    x: '4,9 tỷ/tháng',
    y: '11,3 tỷ/quý (75 tỷ/năm)',
    z: '31/12/2026',
    reason:
      'Pipeline có 40+ trường quan tâm. Nếu chuẩn hóa CRM 100% và tăng demo BGH từ 10 lên 20 buổi/tháng, tỷ lệ chuyển đổi tăng đáng kể.',
    lm1desc: 'Số buổi demo / gặp trực tiếp Ban Giám Hiệu tại trường / tuần',
    lm1target: '≥ 10 buổi / tháng (≥ 3/tuần)',
    lm1owner: 'Sale team Nexta (Lan Anh, Văn Khoa...)',
    lm2desc: 'Số trường tiếp cận mới / tháng + CRM cập nhật 100%',
    lm2target: '≥ 40 trường/tháng · CRM 100% trước 15/6',
    lm2owner: 'GĐ KD Nexta (Nguyễn Diệu Thùy)',
    sbwig: 'DT Nexta: 4,9 tỷ/tháng → 75 tỷ/năm trước 31/12/2026',
    sblag: 'Doanh thu tháng / Số trường ký HĐ',
  },
  joystar: {
    metric: 'Doanh thu Massko | Joystar (AI Camera + Robot AI)',
    x: '3.800 máy tồn kho',
    y: '31,5 tỷ (10.000 máy mới + giải phóng tồn kho)',
    z: '31/12/2026',
    reason:
      'Kênh TT Anh ngữ/VTT có nhu cầu 7.000 máy. Kênh online B2C có thể đạt 3.000 máy với ngân sách digital phù hợp.',
    lm1desc: 'Số đối tác Trung tâm Anh ngữ / VTT ký hợp đồng phân phối mới / tuần',
    lm1target: 'Target đủ để đạt 7.000 máy kênh B2B',
    lm1owner: 'GĐ KD Joystar (Đỗ Thị Đoan)',
    lm2desc: 'Số đơn hàng online B2C / tuần qua các kênh digital',
    lm2target: 'Target đủ để đạt 3.000 máy kênh online',
    lm2owner: 'Marketing Massko',
    sbwig: 'Joystar: 0 → 31,5 tỷ trước 31/12/2026',
    sblag: 'Doanh thu Joystar / Số máy bán ra',
  },
  meup: {
    metric: 'Doanh thu Massko | Meup (Meup M90 + sp hỗ trợ vận động)',
    x: '0 (sản phẩm mới ra thị trường)',
    y: '20 tỷ (12.000 sản phẩm)',
    z: '31/12/2026',
    reason:
      'Kênh phòng khám / nhà thuốc có quy mô lớn. Meup M90 phù hợp nhu cầu người cao tuổi — nếu vào được 100 nhà thuốc/phòng khám trong 7 tháng.',
    lm1desc: 'Số phòng khám / nhà thuốc mới ký hợp đồng phân phối / tuần',
    lm1target: 'Target: đủ để phủ kênh đạt 12.000 sản phẩm',
    lm1owner: 'GĐ KD Meup (Phạm Ngọc Thắng)',
    lm2desc: 'Số Meup M90 + sản phẩm hỗ trợ vận động bán ra / tuần',
    lm2target: '4.000 M90 + 8.000 sp vận động trong 7 tháng',
    lm2owner: 'Sale + Marketing Meup',
    sbwig: 'Meup: 0 → 20 tỷ trước 31/12/2026',
    sblag: 'Doanh thu Meup / Số sản phẩm bán ra',
  },
  support: {
    metric: 'Chỉ số hỗ trợ SBU (theo phân công)',
    x: 'Tình trạng hiện tại',
    y: 'Mục tiêu hỗ trợ',
    z: '31/12/2026',
    reason: '',
    lm1desc: '',
    lm1target: '',
    lm1owner: '',
    lm2desc: '',
    lm2target: '',
    lm2owner: '',
    sbwig: 'WIG hỗ trợ theo phân công BLĐ',
    sblag: 'Chỉ số hỗ trợ',
  },
} as const satisfies Record<SbuId, Record<string, string>>
